2024-10-15 06:30:04 | INFO    | __main__:stash:131 | run - {'image': '20231121', 'version': '0.10.1.post2', 'role': 'EpicPlayer', 'headless': True}
2024-10-15 06:30:13 | INFO    | __main__:claim_epic_games:97 | Try to flush cookie - {'task': 'claim_epic_games'}
2024-10-15 06:30:15 | INFO    | epic_games.agent:_login:237 | login-with-email - {'url': 'https://www.epicgames.com/id/login?lang=en-US&noHostRedirect=true&redirectUrl=https://store.epicgames.com/en-US/free-games&__cf_chl_rt_tk=BPqfOJ.gXzZ8S59ELnug7mu59uC5eiE9pgeriPGK91U-1728945015-1.0.1.1-ewLxJBB7HSAguJK..rxQlxs969CfKO1tbuvaDOA8qTw'}
2024-10-15 06:30:45 | WARNING    | epic_games.agent:authorize:266 | 执行超时 - {'task': 'authorize', 'retry': 0}
2024-10-15 06:30:48 | INFO    | epic_games.agent:_login:237 | login-with-email - {'url': 'https://www.epicgames.com/id/login?lang=en-US&noHostRedirect=true&redirectUrl=https://store.epicgames.com/en-US/free-games&__cf_chl_rt_tk=dbEmGqpgWbVsuaLCwvabv1MENAYIXiCrhmA_WC8ItNQ-1728945048-1.0.1.1-x2leBd2pWqsAMB7bKtaYq0n8ryAG9eh8jHp_ngo.YA0'}
2024-10-15 06:31:18 | WARNING    | epic_games.agent:authorize:266 | 执行超时 - {'task': 'authorize', 'retry': 1}
2024-10-15 06:31:21 | INFO    | epic_games.agent:_login:237 | login-with-email - {'url': 'https://www.epicgames.com/id/login?lang=en-US&noHostRedirect=true&redirectUrl=https://store.epicgames.com/en-US/free-games&__cf_chl_rt_tk=2_VHeA1Z7WdDr1rQCNm1_bBXkFwlGKGQbZSaBkJsKtA-1728945080-1.0.1.1-BIJTd6GiZEJ5OUiNLpmegRXfqfhBRFYI.37EeNGENjk'}
2024-10-15 06:31:51 | WARNING    | epic_games.agent:authorize:266 | 执行超时 - {'task': 'authorize', 'retry': 2}
2024-10-15 06:31:51 | ERROR    | __main__:run:158 | An error has been caught in function 'run', process 'MainProcess' (3819), thread 'MainThread' (140338045598592): - {}
Traceback (most recent call last):
  File "/home/runner/work/epic-awesome-gamer/epic-awesome-gamer/epic/src/claim.py", line 162, in <module>
    asyncio.run(run())
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/home/runner/work/epic-awesome-gamer/epic-awesome-gamer/epic/src/claim.py", line 158, in run
    await agent.stash()
  File "/home/runner/work/epic-awesome-gamer/epic-awesome-gamer/epic/src/claim.py", line 151, in stash
    await self.claim_epic_games(context)
  File "/home/runner/work/epic-awesome-gamer/epic-awesome-gamer/epic/src/claim.py", line 98, in claim_epic_games
    if await epic.authorize(page):
  File "/home/runner/work/epic-awesome-gamer/epic-awesome-gamer/epic/src/epic_games/agent.py", line 269, in authorize
    raise RuntimeError(f"Failed to flush token - agent={self.__class__.__name__}")
RuntimeError: Failed to flush token - agent=EpicGames
